app:
  name: request-processor
  outbox:
    batch-size: 50
    delay-ms: 1000

server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5444/pgProducer
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      connection-timeout: 30000

  jpa:
    hibernate:
      ddl-auto: create-drop  # create, create-drop, validate, none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: false

  sql:
    init:
      mode: always